index.html, lib/Snake.js, lib/index.js, lib/styles.css
snake is starting to move right and left
=> Create Snake class create circle follow movement of mouse right and left

lib/Food.js, lib/Snake.js, lib/index.js
Created food, work on the scroll/gravity function
=> Generate Food, issues with y-axis changes

lib/Ball.js, lib/Paddle.js, lib/index.js
The ball moves and bounces now!!! Will work on the paddle and paddle/ball collision next.
=> Ball is bouncing off walls

lib/Ball.js, lib/Paddle.js, lib/index.js
Still working on collision features
=> Working on paddle/ball collision

lib/Block.js
refactor brick array in creating the wall;
=> Refactor array function

index.html, lib/Ball.js, lib/Block.js, lib/Game.js, lib/Paddle.js, lib/index.js, lib/styles.css
Paddle and ball collision is done. start with start and end game next.
=> Finish paddle collision, work on start and end game

index.html, lib/Ball.js, lib/index.js, lib/styles.css
=> Add end game function

index.html, lib/Block.js, lib/index.js, lib/styles.css
got score to change and store in localStorage!
=> Done with scoring functions

index.html, lib/Ball.js, lib/Block.js, lib/Game.js, lib/LevelUp.js, lib/index.js, lib/styles.css
refactored code to game class. Score currently not working and levels are in process.
=> work on leveling up

lib/Block.js, lib/Game.js, lib/index.js, lib/styles.css
level displays and increments.
=> level displays and increments with new level

index.html, lib/Block.js, lib/Game.js, lib/index.js
=> got levels to work

lib/Ball.js, lib/Block.js, lib/Game.js, lib/Paddle.js, lib/index.js, lib/styles.css, test/Ball-test.js, test/Block-test.js, test/Game-test.js
refractored spaces and saved score after each level
=> refractor paddle

test/Game-Piece-test.js
moved level up and restart functions into the class file
=> moved some functions in index to class

lib/Ball.js, lib/Block.js, lib/Game.js, lib/Paddle.js, lib/index.js
moved restart and level up window
=> Moved restart function to class

lib/Game-Piece.js, test/Game-Piece-test.js
Game-piece class was removed to file
=> Add Game-piece class

lib/Game-Piece.js
Look through to see if we need this.
=> Add game piece

lib/Ball.js, lib/Block.js, lib/Game.js, lib/Paddle.js, lib/index.js
No errors, fixed all issues with lint program
=> Finish lint for project

index.html, lib/Game.js, lib/index.js
Got the final won window to work.
=> Final won window working

lib/Ball.js, lib/Block.js, lib/Game.js, lib/index.js, lib/styles.css, test/Ball-test.js, test/Block-test.js, test/Game-test.js
wrote collision tests for ball, block, and paddle. Linted and refractored spaces.
=> Wrote collision tests, linted, refractored

lib/Game.js, lib/index.js, test/Game-test.js
to make it easier for the user  when the level starts and added game test for ball level up and paddle
=> change ball x on new level
